name: CLARIN.SI schema validate

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Validate:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Setup Java JDK
        uses: actions/setup-java@v1.4.3
        with:
          # The Java version to make available on the path. Takes a whole or semver Java version, or 1.x syntax (e.g. 1.8 => Java 8.x). Early access versions can be specified in the form of e.g. 14-ea, 14.0.0-ea, or 14.0.0-ea.28
          java-version: 1.15
          # The package type (jre, jdk, jdk+fx)
          java-package: jdk
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout jing
        uses: actions/checkout@v2
        with:
          repository: relaxng/jing-trang
          path: jing

      - name: Check java info
        run: |
          echo $(java -version)
          echo $JAVA_HOME

      - name: Build jing
        run: |
          cd $GITHUB_WORKSPACE/jing
          ./ant
      - name: Checkout rsdo-annos
        uses: actions/checkout@v2
        with:
          path: rsdo-annos
      # Runs a set of commands using the runners shell
      #- name: Navigate to repository
      #  run: cd $GITHUB_WORKSPACE/rsdo-annos
      - name: Validate text
        run: |
          cd $GITHUB_WORKSPACE/rsdo-annos
          java -jar $GITHUB_WORKSPACE/jing/build/jing.jar -t bin/tei_clarin.rng rsdo-annos.xml
